# Generated by Django 3.1rc1 on 2020-08-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255, verbose_name='номер и часть статьи')),
                ('name', models.CharField(max_length=1500, verbose_name='название части статьи')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='категория статьи')),
                ('parameters', models.JSONField()),
            ],
            options={
                'verbose_name': 'часть',
                'verbose_name_plural': 'части',
            },
        ),
    ]
