# Generated by Django 3.1rc1 on 2020-08-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='parameters',
            field=models.JSONField(verbose_name='параметры статьи'),
        ),
    ]
