name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: make test